vich_uploader:
    db_driver: orm

    mappings:
        projet_image:
            uri_prefix: /images/projets
            upload_destination: '%kernel.project_dir%/public/images/projets'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
        projet_mp3:
            uri_prefix: /mp3
            upload_destination: '%kernel.project_dir%/public/mp3'

