<?php

namespace ContainerRjyIJyU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BkMzPbZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BkMzPbZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BkMzPbZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'downloadHandler' => ['services', 'vich_uploader.download_handler', 'getVichUploader_DownloadHandlerService', true],
            'projet' => ['privates', '.errored..service_locator.BkMzPbZ.App\\Entity\\Projet', NULL, 'Cannot autowire service ".service_locator.BkMzPbZ": it references class "App\\Entity\\Projet" but no such service exists.'],
        ], [
            'downloadHandler' => '?',
            'projet' => 'App\\Entity\\Projet',
        ]);
    }
}
