<?php

namespace ContainerFKvzxce;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2eG6kDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t2eG6kD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t2eG6kD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
            'soonRepository' => ['privates', 'App\\Repository\\SoonRepository', 'getSoonRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ProjetRepository',
            'soonRepository' => 'App\\Repository\\SoonRepository',
        ]);
    }
}
