<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFKvzxce\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFKvzxce/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFKvzxce.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFKvzxce\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFKvzxce\App_KernelDevDebugContainer([
    'container.build_hash' => 'FKvzxce',
    'container.build_id' => 'f0de918b',
    'container.build_time' => 1610812761,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFKvzxce');
